apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myphp-pv-claim
  labels:
    name: php-storage
    env: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
